### ISSUE TITLE
Generated code assumes std is in scope, sometimes breaks build

### ISSUE THREAD

**Issue by garbageslam** [yaahc/displaydoc#20]
Sometimes, a large project has infrastructure crates that are `#![no_std]`, which get linked into some targets that do have std, and some that don't. So it is desirable to have low-level crates that can build in `#![no_std]` mode, even if `std` feature gets turned on in the `displaydoc` crate during global feature unification.

Because of this code: https://github.com/yaahc/displaydoc/blob/master/src/expand.rs#L24
the build breaks in `displaydoc` generated code:

```
error[E0433]: failed to resolve: use of undeclared type or module `std`
  --> src/fog/report/validation/src/ingest_report.rs:51:17
   |
51 | #[derive(Debug, Display)]
   |                 ^^^^^^^ use of undeclared type or module `std`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0433`.
```

My suggestion is:

The code here is subtly flawed:

```
    quote! {
        trait DisplayToDisplayDoc {
            fn __displaydoc_display(&self) -> Self;
        }

        impl<T: core::fmt::Display> DisplayToDisplayDoc for &T {
            fn __displaydoc_display(&self) -> Self {
                self
            }
        }

        trait PathToDisplayDoc {
            fn __displaydoc_display(&self) -> std::path::Display<'_>;
        }

        impl PathToDisplayDoc for std::path::Path {
            fn __displaydoc_display(&self) -> std::path::Display<'_> {
                self.display()
            }
        }

        impl PathToDisplayDoc for std::path::PathBuf {
            fn __displaydoc_display(&self) -> std::path::Display<'_> {
                self.display()
            }
        }
```

because the generated code is assuming that `std` is in scope. But the calling crate may not have an std feature at all and may be `no_std`.

A friendlier way would be something like,

```
#[cfg(feature = "std")]
extern crate std;
```

in the generated code, to make the generated code self-contained.

**Comment by yaahc** [comment]
I see the issue and agree this should be fixed but I don't understand how your proposed solution would end up fixing it.

So my understanding of your solution is that we'd remove the `std` feature from `displaydoc` itself and instead insert `cfg` statements into the generated code so that the libraries that use `displaydoc` could then be configured for no_std usage. Wouldn't adding the `extern crate std;` statement to the generated code just make it link in `std` even on `no_std` projects? I'm no expert on `no_std` code but this seems like something most ppl would want to avoid...

it seems like the appropriate solution would be to slap `#[cfg(feature = "std")]` onto all of the `PathBuf` referencing impls, but then this seems like it would cause issues where users have to manually add a `[features] std = []` section to their `Cargo.toml` to be able to print Paths and PathBufs in their Display impls, which seems less than ideal as well...

I feel like im missing something >_<

**Comment by yaahc** [comment]
Or wait, is the idea that we'd leave the `std` feature so people can be careful to not even generate this code, but if they do generate this code because they're compiling something that _does_ link against std already then its fine to just extern std? This makes sense.

**Comment by yaahc** [comment]
Should be fixed by the above PR, lmk if that looks good / fixes your issue and I'll merge it and make a new release.
