### ISSUE TITLE
Doesn't work for `Path` and `PathBuf`

### ISSUE THREAD

**Issue by Kixunil** [yaahc/displaydoc#4]
If I have `PathBuf` in one enum variant, it fails to compile because `PathBuf` doesn't implement `Display`. The correct way to display `PathBuf` is by calling display.

I suggest to allow `{0.display()}` to resolve it. More generically, allow both `{0.any_method()}` and `{field.any_method()}`

Nice crate, BTW. :)

**Comment by yaahc** [comment]
Thank you!

I'll see what I can do

**Comment by yaahc** [comment]
I'm looking into doing this, I kinda want to support arbitrary expressions and still allow the debug format to work and I'm not really sure how to go about it properly but I'm doing some research, gonna note down what I'm working on rn so you can see whats happening.

```rust
        assert("The path {0.display()}", "The path {}", "0.display()");
        assert("The path {0.display():?}", "The path {:?}", "0.display()");
```

These are the test cases I'm adding and tentatively would like to be able to support, I'm not positive that it will be easy or possible to parse expressions and disambiguate the :? at the end but hopefully given that its surrounded by `{ }` something will be possible without it being hacky or fragile.

Right now parsing works like this, we get to the string and find a format str, then we peak at the first character and do the following checks

```rust
            let var = match next {
                '0'..='9' => take_int(&mut read),
                'a'..='z' | 'A'..='Z' | '_' => take_ident(&mut read),
                _ => return,
            };
```

where `take_ident` is implemented as such

```rust
fn take_ident(read: &mut &str) -> String {
    let mut ident = String::new();
    for (i, ch) in read.char_indices() {
        match ch {
            'a'..='z' | 'A'..='Z' | '_' => ident.push(ch),
            _ => {
                *read = &read[i..];
                break;
            }
        }
    }
    ident
}
```

and take_int is very similar. I'll need to figure out how to implement a `take_expr` that can accurately tell when it has hit the end of a valid expression. Lets see how it goes!

**Comment by yaahc** [comment]
From the discussion it seems like a couple of breaking changes would be necessary to make this work.

First of all we need some way disambiguate numbers that are identifiers for unnamed members and actual integer literals. Heres an example of the problem

```rust
/// print this expr {random_module::some_fn(0)}
Variant(String),
```
does `some_fn` get a literal `0` or the String contained in the variant as 0?

The way that we currently make bindings to these unnamed fields in order to even refer to them in the arguments list of the `write!` call is by prefixing the number with an underscore. So `/// {0}` becomes `let Variant{ _0 } = self; write!(formatter, "{}", _0);`

My plan is to make this a user facing feature, so that all format strings for unnamed parameters have to include the prefix. So you would write `/// {_0}` or `/// some expr output {some_fn(0, _0)}`

I think this solution strikes a nice balance between gross syntax and user discoverability. In order to use the formatting for unnamed parameters at all you have to learn about how we bind to them, and once you do that its immediately obvious how to disambiguate them from other numbers. We can also add a check for `{0}` and produce an error saying that it needs a `_` prefix or the `{ }` should be removed if they intended to print a literal 0.

The next issue is dealing with the formatting suffix. right now we support expressions like `{0:?}`, dealing with this suffix and figuring out exactly where the expression ends and the format specifier begins seems... challenging.

My proposed solution for now is to require parens around the expr when you want to use a suffix. This is pretty gross though so I am very open to alternative suggestions. So you would write something like `{_0}` or `{(_0):?}` We can very easily find matching parens and just lift out the entire expression inside of it and leave the format specifier behind in the format string and let the format! macros handle printing errors if people put improper format strings in the doc comment. We require that the character after the closing `)` MUST be a `:` and give an explicit / helpful error to tell people to use a formatting string in that case.  I'm worried about the case when someone uses the format string without the paren a la `{_0:?}` and what kind of errors we would produce for that. I imagine it could get really gnarly, especially if the type ascription feature is enabled in the user's crate. We can maybe lint for the obvious case of `:?}` or maybe we could just explicitly allow that one case, but I'm not confident this is a good solution...

**Comment by yaahc** [comment]
# Alternative Impl

@dtolnay has noted that this could be bypassed for `Path` and `PathBuf` specifically by using autoref style specialization

https://github.com/dtolnay/case-studies/blob/master/autoref-specialization/README.md#simple-application

This can be done without a breaking change I believe, so it might be better to go with this first and then try to implement the arbitrary expression version later if people start asking for it.

**Comment by yaahc** [comment]
```rust
use core::fmt::Display;
use std::path::Path;

trait DisplayToDisplayDoc {
    fn get_display(&self) -> Self;
}

impl<T: Display> DisplayToDisplayDoc for &T {
    fn get_display(&self) -> Self {
        self
    }
}

trait PathToDisplay {
    fn get_display(&self) -> std::path::Display<'_>;
}

impl<T: AsRef<Path>> PathToDisplay for T {
    fn get_display(&self) -> std::path::Display<'_> {
        self.as_ref().display()
    }
}

fn main() {
    let p = Path::new("/var/log/happy");
    println!("{}", (&p).get_display());
    let p: i32 = 1;
    println!("{}", (&p).get_display());
}
```

This works like a charm, the main issues with this are

1. its not `no_std` compatible I think, so this will have to only be enabled on std because there is no `core::path` equivalent for `std::path`
2. We need to detect when we're using display vs debug and only route through this trait when we're using display

**Comment by Kixunil** [comment]
Oh, that's a nice trick! I agree this is a good approach. Thanks for implementing it!

**Comment by yaahc** [comment]
Thanks! And thanks for the idea, I hope to get a new release out soon, I just need to verify that none of the changes I made can leak types into people's public API or docs and I want to get some quick sanity code review from a friend too.
