### ISSUE TITLE
Include full example

### ISSUE THREAD

**Issue by vitiral** [yaahc/displaydoc#5]
You give the example code, but you don't give what it will display as! For instance, will `DataStoreError::Disconnect` display as

```
data store disconnected
```

or

```
DataStoreError::Disconnect(data store disconnected)
```

Or... something else?

**Comment by vitiral** [comment]
Love the crate BTW, awesome idea!

**Comment by yaahc** [comment]
It should render just the content of the comment, so the former. As for a full example, that's a great idea!

I'm not sure when I'll be able to get around to adding it, hopefully not too long because it seems like it should be relatively straight forward, but if you want to go ahead and open a PR to add the example I will merge it right away.
